name: Build container
# Run this action on any pull request, push to the master branch, and every night at midnight
on:
  pull_request: {}
  push:
    branches:
      - 'releases/*'
  
jobs:
  registry_ghes:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2

      - name: Push result to GPR if a push to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
            echo Hello
